### ISSUE TITLE
git clone https://github.com/NvChad/starter ~/.config/nvim && nvim

### ISSUE THREAD

**Issue by yellmean** [NvChad/starter#13]
Error detected while processing /home/nvim/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/nvim/.config/nvim/init.lua:17: module 'lazy' not found:
        no field package.preload['lazy']
        no file './lazy.lua'
        no file '/__w/neovim/neovim/.deps/usr/share/luajit-2.1/lazy.lua'
        no file '/usr/local/share/lua/5.1/lazy.lua'
        no file '/usr/local/share/lua/5.1/lazy/init.lua'
        no file '/__w/neovim/neovim/.deps/usr/share/lua/5.1/lazy.lua'
        no file '/__w/neovim/neovim/.deps/usr/share/lua/5.1/lazy/init.lua'
        no file './lazy.so'
        no file '/usr/local/lib/lua/5.1/lazy.so'
        no file '/__w/neovim/neovim/.deps/usr/lib/lua/5.1/lazy.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /home/nvim/.config/nvim/init.lua:17: in main chunk

**Comment by siduck** [comment]
rm -rf old nvim dirs. and please use neovim 0.9.5 at least

**Comment by siduck** [comment]
can you  make a video out of it? do a clean installation, also what is your git version

**Comment by yellmean** [comment]
It's my git version old, Now It's normal after update git to version 2.29. Thanks!
