### ISSUE TITLE
UI - statusline modules `order` config doesn't work

### ISSUE THREAD

**Issue by SPiCaRiA** [NvChad/starter#16]
Hi, I'm trying to migrate my statusline settings from `overriden_modules` to the `modules` field as shown in the [NvChad UI Configuration](https://nvchad.com/docs/config/nvchad_ui).

However when I tried to set the `order` of statusline modules, I simply got this error and not surprisingly it didn't work:

<img width="1195" alt="Screenshot 2024-04-01 at 16 40 43" src="https://github.com/NvChad/starter/assets/11176415/8ad6803f-5ff0-470c-9ed0-3536d4e55ca1">

My code:

```lua
  statusline = {
    -- Old
    -- overriden_modules = function(modules)
    --   -- Show column number in statusline
    --   table.insert(modules, 9, "%#St_ln_col#" .. " Ln %l, Col %c ")
    -- end,
    modules = {
      order = { "mode", "file", "git", "%=", "lsp_msg", "%=", "diagnostics", "lsp", "cursor_loc", "cwd", "cursor" },
      cursor_loc = function()
        return "%#St_ln_col#" .. " Ln %l, Col %c "
      end,
    },
  },

```

------
The doc and `nvconfig.lua` both implies that `order` is indeed an array though 🤔 :

```lua
...
  statusline = {
    -- more opts
    order = {...}, -- check stl/utils.lua file in ui repo 
    modules = {
      -- The default cursor module is override
      cursor = function()
        return "%#BruhHl#" .. " bruh " -- the highlight group here is BruhHl      end,
    }
  }
...
```

and `nvconfig.lua`:

```lua
...
  statusline = {
    theme = "default", -- default/vscode/vscode_colored/minimal
    -- default/round/block/arrow separators work only for default statusline theme
    -- round and block will work for minimal theme only
    separator_style = "default",
    order = nil,
    modules = nil,
  },

  tabufline = {
    enabled = true,
    lazyload = true,
    order = { "treeOffset", "buffers", "tabs", "btns" },
    modules = nil,
  },
...
```

**Comment by SPiCaRiA** [comment]
Btw there's a typo in the official doc, we lose the function `end` 🤣 

> ```lua
>       cursor = function()
>         return "%#BruhHl#" .. " bruh " -- the highlight group here is BruhHl      end,
> ```

**Comment by siduck** [comment]
![image](https://github.com/NvChad/starter/assets/59060246/e1590e46-ac06-4a9e-817d-478daef1367a)


order is  in root of statusline table, not inside modules

**Comment by siduck** [comment]
> Btw there's a typo in the official doc, we lose the function `end` 🤣
> 
> > ```lua
> >       cursor = function()
> >         return "%#BruhHl#" .. " bruh " -- the highlight group here is BruhHl      end,
> > ```

yea, but users must know at least basic lua to debug it xD

**Comment by SPiCaRiA** [comment]
> ![image](https://private-user-images.githubusercontent.com/59060246/318398953-e1590e46-ac06-4a9e-817d-478daef1367a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMTQ3MjMsIm5iZiI6MTcxMjAxNDQyMywicGF0aCI6Ii81OTA2MDI0Ni8zMTgzOTg5NTMtZTE1OTBlNDYtYWMwNi00YTllLTgxN2QtNDc4ZGFlZjEzNjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDIzMzM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4ZWJmMGJiMmI3YjE1MDgxNjA2ZmFhMWZhYjc2NDk5NGZmZjRmMDZmMzZkZDc4NjI3ZmY0OGM3OTI4N2M0ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fcE_i55h6pg2a3SYH08aPB6u70GlVB3lmg8stouUDQs)
> 
> order is in root of statusline table, not inside modules

Ah I missed that part for some reasons 🤣 Thank you so much
