### ISSUE TITLE
Change LICENSE to a permissive one

### ISSUE THREAD

**Issue by lingling9000** [NvChad/starter#20]
First I want to clear out: **I absolutely agree that the main NvChad project is under GPL** or whatever license you prefer to protect your work under the open source philosophies!

But this _starter_ configuration is intended to be a skeleton for the user configuration to make use of NvChad. Most users will have much more self written code than provided code from this repository. Therefore I think the starter config should be under a more permissive license.

I'm especially concerned about adding my self-written [lua_snippets](https://codeberg.org/lingling/dotfiles-nvchad/src/branch/main/custom/lua_snippets) into a GPL protected configuration, because I cannot estimate how the license inheritance will affect the resulting code when I use the snippets.

For this starter configuration I would recommend a [public-domain-equivalent license](https://en.wikipedia.org/wiki/Public-domain-equivalent_license), e. g.:

- 0BSD
- [UNLICENSE](https://unlicense.org/) 

I think something like MIT to have attribution would also be fine.

**Comment by siduck** [comment]
i dont see how your snippets would matter the GPL licence, you're supposed to fork this repo or delete its .git and store it in your dotfiles repo

**Comment by lingling9000** [comment]
I know, that is exactly how I understand this starter Repo. But after forking and modifying this starter configuration, the resulting code need to be regarded as derived work of an GPL-licensed project and therefore also released under the terms of the GPL. 

Which is 100% fine the NvChad main repo. But for this starter configuration, which is basically just a minimal example and skeleton, it is too extensive. In order to comply with the GPL, it is necessary that everyone who forks this repo for their own configuration also places it under the GPL if they want to publish their dotfiles. That is the purpose of the GPL. 

Other people can't release their nvim dotfiles based on this starter under another license than GPL. But most folks will have much more own code than code from this repo in their configuration. And they should have a free choice under which license they release their work. Thats why I recommend a public-domain-equivalent license for this starter configuration.

**Comment by siduck** [comment]
hmmm, ig no license for it would be good

**Comment by lingling9000** [comment]
Thanks for your understanding so far!

Unfortunately, in the complete absence of a license, the project must be considered proprietary. I didn't make that up, you can read about it at e. g. [choosealicense.com](https://choosealicense.com/no-permission/):

> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software.

That's why I recommend e. g. [UNLICENSE](https://unlicense.org/) for a starter config.
