### ISSUE TITLE
Lsp diagnostic - "undefined type or alias `chadrcConfig`

### ISSUE THREAD

**Issue by kert-daiki** [NvChad/starter#21]
Hi, I hope you're well 

I get this warning  in lsp when open chardrc.lua file 

![image](https://github.com/NvChad/starter/assets/64678724/0e904880-c040-4a59-8dd8-00584a3829c9)
![image](https://github.com/NvChad/starter/assets/64678724/afc8db45-2b0e-40af-af1b-5ad568e46daa)

Do you know what ChadrcConfig does?

**Comment by siduck** [comment]
this will happen if you setup lua_ls without any types, i'm assuming u did it in your lspconfig.  If you dont include it then nvchad's default lua_ls setup is called which has types, either copy our code or dont include lua_ls in your lspconfig
