### ISSUE TITLE
Windows overlaying each other

### ISSUE THREAD

**Issue by qbnil** [NvChad/starter#40]
![Shot-2024-08-24-220505](https://github.com/user-attachments/assets/1f892748-f966-42b4-a7d7-244017c8b282)
Is there any way i can position these windows normally and also get rid of the border in one of the windows, thx...

**Comment by siduck** [comment]
turn off the signature.. how small is your screen? it should usually show under the cursor if there's space

https://github.com/NvChad/ui/blob/v2.5/lua/nvconfig.lua#L78

**Comment by qbnil** [comment]
I got a 15.6 laptop. I got what you mean. How do i get rid of the ligature window's border then

**Comment by qbnil** [comment]
![image](https://github.com/user-attachments/assets/9a95b486-6819-44ef-96e7-65b85336b3a0)
the problem is that the ligature window still apears when there is a " inside (). It'd be awesome if i could get rid of that feature and only leave the window when the first curly is being types -> ( ....

**Comment by qbnil** [comment]
![image](https://github.com/user-attachments/assets/5a6cca03-fbec-4945-857a-3d8bef13b861)
this way before the " it works perfectly

**Comment by siduck** [comment]
hmmm  not really, cuz typing " wont get u cmp completions, so signature is visible

**Comment by siduck** [comment]
the signature module checks if current/previous char have triggered chars from lsp

https://github.com/NvChad/ui/blob/v2.5/lua/nvchad/lsp/signature.lua#L18

**Comment by qbnil** [comment]
> hmmm not really, cuz typing " wont get u cmp completions, so signature is visible
![image](https://github.com/user-attachments/assets/c2ae499a-29f6-42d5-85db-8e24a059c229)
the second i type " the completion menu appears and overlays the signature window

**Comment by qbnil** [comment]
i also noticed that this happens when there is no space for either cmp window down below or above like here:
![image](https://github.com/user-attachments/assets/2c33349c-51ee-4bd9-bc32-2868fe8738a3)

**Comment by qbnil** [comment]
In the middle of the screen everything is perfect:
![image](https://github.com/user-attachments/assets/b443b7a9-3425-49aa-956d-892438f8f34f)

**Comment by qbnil** [comment]
i'm really struggling bruhh.. i can't disable lsp signature border... and cmp documentation border... 
    config = function(_, opts)
      local cmp = require "cmp"

      local myopts = {
        -- sources = {
        --   { name = "nvim_lsp_signature_help" },
        -- },
        window = {
          documentation = {
            border = "none",
          },
        },
        mapping = {
          ["<A-a>"] = cmp.mapping.confirm({ select = false }),
          ["<A-e>"] = cmp.mapping.abort(),
          ["<C-b>"] = cmp.mapping.scroll_docs(-4),
          ["<C-f>"] = cmp.mapping.scroll_docs(4),
        },
      }

      opts = vim.tbl_deep_extend("force", myopts, opts)
      require("cmp").setup(opts)
i tried to override like that but that didn't seem to work

**Comment by qbnil** [comment]
nevermind, fixed this..
is there any way to delete the default mapping, because <CR> be bugging sometimes because by default it's mapped to confirm selection

**Comment by qbnil** [comment]
just set it to nil and it worked..

**Comment by siduck** [comment]
> just set it to nil and it worked..

yes thats the way, in neovim, tables with keys/values   must need their keys = nil for deleting them
