### ISSUE TITLE
Override cmp default mappings

### ISSUE THREAD

**Issue by qbnil** [NvChad/starter#41]
Ik that in nvchad config i could do this in chadrc file M.cmp = { .... and override the mappings here but how do i do that in this case. I tried overriding myself but every override just wipes all the default cmp settings which were brought by nvchad...

**Comment by siduck** [comment]
```lua
  {
    "hrsh7th/nvim-cmp",
    opts = {
      mapping = {
        ["<CR>"] = cmp.mapping(function(fallback)
          fallback()
        end),
        ["<C-o>"] = cmp.mapping.confirm {
          behavior = cmp.ConfirmBehavior.Insert,
          select = true,
        },
      },
    },
  },
  ```
  
  try this, and checks if its breaking lazyloading i.e loading cmp on startup

**Comment by qbnil** [comment]
Thx for that :)

**Comment by siduck** [comment]
> Thx for that :)

you can directly modify opts table too, instead of merging

```lua
opts.mapping ["<CR>"] = cmp.mapping(function(fallback)
            fallback()
          end)
        ```

**Comment by qbnil** [comment]
Thx again, that was exactly what i needed
