### ISSUE TITLE
attempt to index field 'uv'

### ISSUE THREAD

**Issue by pubaayaam** [NvChad/starter#45]
Hello,

  I am presented with below message from the initial setup,

`Error detected while processing /home/prakashsinhaba/.config/nvim/init.l
ua:
E5113: Error while calling lua chunk: /home/prakashsinhaba/.config/nvim/
init.lua:7: attempt to index field 'uv' (a nil value)
stack traceback:
        /home/prakashsinhaba/.config/nvim/init.lua:7: in main chunk
E484: Can't open file /usr/share/nvim/syntax/syntax.vim
Press ENTER or type command to continue`

Instruction followed :=
  I followed instruction from link https://nvchad.com/docs/quickstart/install/

**Comment by siduck** [comment]
use neovim 0.10

**Comment by pubaayaam** [comment]
able to progress 
with a snap 
install...
