### ISSUE TITLE
How to change nvim-tree configuration??

### ISSUE THREAD

**Issue by matutetandil** [NvChad/starter#49]
I'd like to add options to the `view` table for instance: `adaptive_size = true` or `relativenumber = true`, or modify the `filters` table.

How do I do that??

I couldn't find anything in the docs...

I followed the install procedure in the docs. So my `.config/nvim` directory looks like this:

```shell
|-- LICENSE
|-- README.md
|-- init.lua
|-- lazy-lock.json
`-- lua
    |-- chadrc.lua
    |-- configs
    |   |-- conform.lua
    |   |-- lazy.lua
    |   `-- lspconfig.lua
    |-- mappings.lua
    |-- options.lua
    `-- plugins
        `-- init.lua
```

Thank you

**Comment by siduck** [comment]
this shows examples of overriding plugin opts https://nvchad.com/docs/config/plugins

**Comment by matutetandil** [comment]
Thank you!!! that worked!! :-)
