### ISSUE TITLE
Theme change error

### ISSUE THREAD

**Issue by Aman1337g** [NvChad/starter#51]
I had installed NvChad using the starter kit about 2 months ago. Today, I updated the installed plugins using Lazy.nvim when NvChad ui 3.0 released. 

When I am selecting a theme using `<leader> + th` and pressing enter , it is showing some error. How to fix this ?

![Screenshot from 2024-10-12 14-13-28](https://github.com/user-attachments/assets/a3982efd-748d-4898-8601-408ffaf39bcf)

Also, can you tell me how to enable the nvdash plugin ? 😅

**Comment by siduck** [comment]
move your theme options to M.base46 instead of M.ui. check the pinned issue on nvchad main repo, this change was notified months ago
