### ISSUE TITLE
E5113: Error while calling lua chunk: /home/chris/.config/nvim/init.lua:7: attem pt to index field 'uv' (a nil value) 

### ISSUE THREAD

**Issue by chrisonlinux** [NvChad/starter#56]
Hello,

I was following the installation instructions on the project's website, and I ran the simple command `git clone https://github.com/NvChad/starter ~/.config/nvim && nvim
`
Instead of the installation continuing, I get this error message: `Error detected while processing /home/chris/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/chris/.config/nvim/init.lua:7: attem
pt to index field 'uv' (a nil value)
stack traceback:
        /home/chris/.config/nvim/init.lua:7: in main chunk
Press ENTER or type command to continue
`

I use Debian unstable (sid) and the version of neovim is 0.9.5. I also have a lua interpreter installed. 
The problem seems to be in the init.lua file here: [https://github.com/NvChad/starter/tree/main/init.lua](url)

How do you think we can fix it?

Thanks!

**Comment by siduck** [comment]
v0.10 is needed

**Comment by chrisonlinux** [comment]
Thank you for the information! I am sorry for opening a meaningless issue.
