### ISSUE TITLE
Docs never show how "how to use the nvchad repo as a plugin."

### ISSUE THREAD

**Issue by AddictArts** [NvChad/starter#6]
Followed the docs and I am missing how to actually use the remaining parts of this. It is appreciated, but this starter is confusing and miss directs. The docs say start and add NvChad, but never actually show how or mention how, so I am lost.

I watched a great video for this and it had you clone the main NvChad repo, but I guess those instructions are now out of date.

Thanks

**Comment by siduck** [comment]
https://github.com/NvChad/starter check the main init.lua file, its very self explanatory

**Comment by AddictArts** [comment]
For anyone else like me who was hopping something in the doc would confirm it, in fact the init.lua will load the other repo as a plugin. I think that is correct in terms of language. It would be a little better if there was some confirmation and mention before getting so far into the docs. Since this step is performed early, installation. Thanks for the excellent work and fast response.

**Comment by siduck** [comment]
https://nvchad.com/docs/config/walkthrough#main_config_structure
