### ISSUE TITLE
starter init.lua has warning "The same file is required with diffeent names" is this expected?

### ISSUE THREAD

**Issue by AddictArts** [NvChad/starter#7]
When performing :e $MYVIMRC and inspecting, init.lua has a warning once the LSP warms up. While just a warning as I'm very new to this it would be great to understand it and be sure I didn't somehow miss a step. Thanks in advance.

This lline

```
require("lazy").setup({
```

**Comment by siduck** [comment]
that warning is normal, nothing to worry about
