### ISSUE TITLE
Following the instructions, this repo clones v2.0 branch of base46 

### ISSUE THREAD

**Issue by metalelf0** [NvChad/starter#8]
Hi, maybe I'm doing something wrong, but fetching this repo and letting it all do the magic seems to clone the v2.0 branch of base46 instead of the newly released 2.5 under `lazy/base46`.

Trying to force the branch to `v2.5` results in "module 'nvconfig' not found" error, so it looks like this starter repo is still made to work with 2.0, right?

Thanks and keep up the great work :)

**Comment by siduck** [comment]
starter repo just clones the v2.5 version of nvchad which has this https://github.com/NvChad/NvChad/blob/v2.5/lua/nvchad/plugins/ui.lua

rm -rf .local/share/nvim and try
